### ISSUE TITLE
'npm run test' failes

### ISSUE THREAD

**Issue by timjb** [SReichelt/slate#80]
Error message:

```
 FAIL  src/shared/logics/__tests__/renderLibrary.test.ts (8.197 s)
  ● render hlm library

    expect(received).resolves.toMatchSnapshot(hint)

    Snapshot name: `render hlm library: 1.5.26 Essentials/Functions/Application%20of%20function%20and%20inverse%20is%20neutral 1`

    - Snapshot  - 1
    + Received  + 4

      Proposition 1.5.26.  Let X, Y be sets, f : X ↔ Y be a bijection, x ∈ X. Then:

        f^-1(f(x)) = x

    - No proof.
    + Proof.
    +
    + f^-1 ∘ f = id_X by definition of f^-1 ⇒^(def) ∀ z ∈ X : f^-1(f(z)) = z
    +  ⇒^(x ∈ X) f^-1(f(x)) = x

      55 |     };
      56 |     let renderedText = renderAsText(renderedDefinition, options);
    > 57 |     expect(renderedText).resolves.toMatchSnapshot(formatItemNumber(itemInfo.itemNumber) + ' ' + uri);
         |                                   ^
      58 |   }
      59 | }
      60 | 

      at Object.toMatchSnapshot (node_modules/expect/build/index.js:198:20)
      at src/shared/logics/__tests__/renderLibrary.test.ts:57:35
      at node_modules/tslib/tslib.js:114:75
      at Object.__awaiter (node_modules/tslib/tslib.js:110:16)
      at checkItem (src/shared/logics/__tests__/renderLibrary.test.ts:46:20)
      at src/shared/logics/__tests__/renderLibrary.test.ts:28:15
      at fulfilled (node_modules/tslib/tslib.js:111:62)

  ● render hlm library

    expect(received).resolves.toMatchSnapshot(hint)

    Snapshot name: `render hlm library: 1.5.27 Essentials/Functions/Application%20of%20function%20after%20inverse%20is%20neutral 1`

    - Snapshot  - 1
    + Received  + 4

      Proposition 1.5.27.  Let X, Y be sets, f : X ↔ Y be a bijection, y ∈ Y. Then:

        f(f^-1(y)) = y

    - No proof.
    + Proof.
    +
    + f ∘ f^-1 = id_Y by definition of f^-1 ⇒^(def) ∀ z ∈ Y : f(f^-1(z)) = z
    +  ⇒^(y ∈ Y) f(f^-1(y)) = y

      55 |     };
      56 |     let renderedText = renderAsText(renderedDefinition, options);
    > 57 |     expect(renderedText).resolves.toMatchSnapshot(formatItemNumber(itemInfo.itemNumber) + ' ' + uri);
         |                                   ^
      58 |   }
      59 | }
      60 | 

      at Object.toMatchSnapshot (node_modules/expect/build/index.js:198:20)
      at src/shared/logics/__tests__/renderLibrary.test.ts:57:35
      at node_modules/tslib/tslib.js:114:75
      at Object.__awaiter (node_modules/tslib/tslib.js:110:16)
      at checkItem (src/shared/logics/__tests__/renderLibrary.test.ts:46:20)
      at src/shared/logics/__tests__/renderLibrary.test.ts:28:15
      at fulfilled (node_modules/tslib/tslib.js:111:62)
```

**Comment by SReichelt** [comment]
That is a snapshot test to make sure that rendering-related modifications don't break anything. It renders the current state of the library, so must be updated (using `npm run test-accept`) whenever the library changes. I forgot to do that, and will close this issue when done. At some point, the rendering test will probably have to be pinned to a specific library commit.

However, even after the fix, `npm run test` still fails due to the errors in the library check, as one proof in particular relies on features that are not yet implemented (#21 and #29).
